# Generated by Django 3.2 on 2023-11-26 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile1', models.IntegerField(blank=True, null=True)),
                ('mobile2', models.IntegerField(blank=True, null=True)),
                ('latitude', models.CharField(max_length=255)),
                ('langitude', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('icons', models.ImageField(blank=True, null=True, upload_to='services')),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.carmodels')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsedCarsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('image', models.ImageField(upload_to='used_car_image')),
                ('used_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usedcar')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoadAssistantRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('langtiude', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usercars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='my_history')),
                ('service', models.ManyToManyField(related_name='myhistory', to='app.Services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BranchSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('slot_number', models.IntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.branches')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.branchslot')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.timing')),
                ('user_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usercars')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('compatible_with', models.ManyToManyField(related_name='accessories', to='user.CarModels')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
