# Generated by Django 3.2 on 2023-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bookaccessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
