# Generated by Django 3.2 on 2023-11-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedcar',
            options={'verbose_name_plural': 'Used Cars'},
        ),
    ]
