# Generated by Django 3.2 on 2023-11-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usedcar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
