# Generated by Django 3.2 on 2023-11-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_notes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.branches'),
        ),
    ]
