# Generated by Django 3.2 on 2023-11-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='branch_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.branches'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.timing'),
        ),
    ]
