# Generated by Django 3.2 on 2023-11-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20231128_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='book_a_service', to='app.Services'),
        ),
    ]
