# Generated by Django 3.2 on 2023-11-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20231129_1325'),
        ('app', '0013_technicalassistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaccessories',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.branches'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.branches'),
        ),
        migrations.AlterField(
            model_name='branchslot',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.branches'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.branches'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.branches'),
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
    ]
