# Generated by Django 3.2 on 2023-12-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20231129_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='description',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='images'),
        ),
    ]
