# Generated by Django 3.2 on 2023-12-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_maintenanceschedule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhistory',
            name='using_points',
            field=models.BooleanField(default=False),
        ),
    ]
