# Generated by Django 4.2+

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_service_category_and_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="customer_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
