# Generated by Django 3.2 on 2023-11-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercars',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercars',
            name='plate_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
