# Generated by Django 3.2 on 2023-12-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20231129_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history_points',
            field=models.IntegerField(default=0),
        ),
    ]
