# Generated by Django 3.2 on 2023-12-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_history_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mypoints',
            field=models.IntegerField(default=20),
        ),
    ]
