# Generated by Django 3.2 on 2023-12-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_mypoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history_points',
            field=models.IntegerField(default=20),
        ),
    ]
