# Generated by Django 3.2 on 2023-12-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypoints',
            name='point_per_pound',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
