# Generated by Django 3.2 on 2023-12-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_loyaltypoints_point_per_pound'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_token',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
