# Generated by Django 4.x

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0021_user_next_service_date_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercars",
            name="is_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
