# Generated by Django 4.2.16 on 2026-05-04 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_serviceitem_price_booking_selections'),
        ('user', '0024_branches_description_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercars',
            name='allow_user_edit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('kind', models.CharField(choices=[('admin_message', 'Admin message'), ('booking_moved', 'Booking rescheduled'), ('booking_status', 'Booking status')], db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='app.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
