# Generated by Django 4.2.16 on 2026-05-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user_notifications_and_allow_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='langitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branches',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
